import {MESSAGE_CONFIRM_USER, MESSAGE_RESET_PASSWORD} from './message';
import {LIFETIME_REFRESH_TOKEN, LIFETIME_EMAIL_TOKEN, LIFETIME_ACCESS_TOKEN, TOKENS_NAME_DATA} from './token';

export {
  MESSAGE_CONFIRM_USER,
  MESSAGE_RESET_PASSWORD,
  LIFETIME_REFRESH_TOKEN,
  LIFETIME_EMAIL_TOKEN,
  LIFETIME_ACCESS_TOKEN,
  TOKENS_NAME_DATA
}
